### ISSUE TITLE
schema: Revert back to 0.1.0 semver

### ISSUE THREAD

**Issue by yarikoptic** [dandi/dandi-cli#472]
Followup to https://github.com/dandi/dandi-cli/pull/460#issuecomment-797641944 and decision was made during the squat meeting - instead of messing with `-rc` suffix we will drop back to some 0.MINOR.PATCH (e.g. could start with 0.1.0 to arbitrarily not start with 0.0.0) version and continue with semver, while incrementing MINOR for breaking changes and PATCH for non-braking enhancements and fixes.

TODOs
- [x] add a const and go to 0.1.0 (part of #460)
- [ ] add semantic to dandi-api (and possibly web ui) component to declare minor supported version within the `0.` series and allow for increments of PATCH without requiring any changes to the components (https://github.com/dandi/dandi-api/issues/155)
- [ ] establish provenance for the schema: #469
- [ ] make dandi-api inform clients about supported metadata version(s): https://github.com/dandi/dandi-api/issues/36 (also related: https://github.com/dandi/dandi-api/issues/119)
- [ ] remove (after all clients adjusted to go for 0.x.y versions) 1.0.0-rc1 from  https://github.com/dandi/schema/tree/master/releases/ to avoid confusion

@waxlamp anything else relating?

**Comment by yarikoptic** [comment]
well, some steps were taken, and we are progressing forward within 0.x., so I will just close this one
